<?php

namespace api_worker\modules\v1\controllers;

use api_worker\modules\v1\api\SiteAPI;
use api_worker\modules\v1\helpers\StateCode;
use common\components\ControllerAPI;
use common\helpers\security\SecurityHelper;
use common\helpers\utils\UtilsHelper;
use common\traits\APISiteTrait;
use Yii;

/**
 * Default controller for the `v1` module
 */
class SiteController extends ControllerAPI
{

	/**
	 * 通用trait
	 *
	 * @see  \common\traits\APISiteTrait::actionFindPassword()
	 * @see  \common\traits\APISiteTrait::actionFindPasswordCode()
	 * @see  \common\traits\APISiteTrait::actionSignUp()
	 * @see  \common\traits\APISiteTrait::actionSignUpCode()
	 */
	use APISiteTrait;

	public function _init()
	{
		parent::_init(); // TODO: Change the autogenerated stub
	}

	/**
	 * 小帮登录
	 * @return array
	 */
	public function actionProviderLogin()
	{

		if ($this->api_version == '1.0') {
			if (YII_ENV_DEV || YII_ENV_TEST) {
				if (!SecurityHelper::checkTestMobile(SecurityHelper::getBodyParam("account"))) {
					$this->_message = "请到应用市场重新下载最新版本";
					$this->_code    = StateCode::COMMON_OPERA_ERROR;

					return $this->response();
				}
			}

			$data = SiteAPI::providerLoginV10();    //TODO 封号禁止登录
			if ($data) {
				$this->_message = "登录成功";
				$this->_data    = $data;
			} else {
				$this->_code    = StateCode::USER_PROVIDER_LOGIN_FAILED;
				$this->_message = "手机或者密码不正确";
			}
		}

		return $this->response();
	}

	/**
	 * 小帮基本配置
	 */
	public function actionProviderConfig()
	{

		if ($this->api_version == '1.0') {
			$this->_data = SiteAPI::providerConfigV10();
		}

		return $this->response();
	}

	/**
	 * 小帮登出
	 */
	public function actionProviderLogout()
	{
		if ($this->api_version == 1.0) {
			SiteAPI::providerLogoutV10();
			$this->_message = "登出成功";
		}

		return $this->response();
	}
}
