<?php
/**
 * @link http://www.281.com.cn/
 * @copyright Copyright (c) 2014 中山市中辰信息科技有限公司
 * @license http://www.281.com.cn/license
 * User: Andy Wong(黄燕弟)
 * Date: AndyWong 2017/6/30
 */

namespace common\helpers\utils;


class ArrayHelper extends \yii\helpers\ArrayHelper
{
	/**
	 * 重写合并数组方法(1.去重复;2.去数组空值)
	 * array_filter		第二个参数为空,默认过滤false值
	 * array_flip	    (第一次:翻转数组，你将会得到唯一键值的数组;第二次:然后再翻转一次，将键和值重新放置，然后得到数组)
	 * @param array $a
	 * @param array $b
	 * @return array|null
	 */
	public static function merge($a, $b)
	{
		return array_flip(array_flip(array_filter(parent::merge($a, $b)))); // TODO: Change the autogenerated stub
	}

}