<?php
/**
 * @link http://www.281.com.cn/
 * @copyright Copyright (c) 2014 中山市中辰信息科技有限公司
 * @license http://www.281.com.cn/license
 * User: Andy Wong(黄燕弟)
 * Date: AndyWong 2017/9/29
 */
namespace wechat\controllers;

use yii\web\Controller;
use Yii;

/**
 * Site controller
 */
class OauthController extends Controller
{
	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function actionLogin()
	{
		if (Yii::$app->mp_wechat->isAuthorized()) {

			$targetUrl = Yii::$app->mp_wechat->getReturnUrl();
			header('location:' . $targetUrl); // 跳转到 user/profile
		}

		return $this->redirect(['site/error']);
	}
}
