<?php
/**
 * @link http://www.281.com.cn/
 * @copyright Copyright (c) 2014 中山市中辰信息科技有限公司
 * @license http://www.281.com.cn/license
 * User: Andy Wong(黄燕弟)
 * Date: AndyWong 2018/4/11
 */

namespace wechat\controllers;

use wechat\helpers\WxClientHelper;


/**
 * Wx controller
 */
class WxController extends ControllerAuthorize
{
	public $apiAddress;

	public function init()
	{
		$this->layout = 'content';

		if (YII_ENV_DEV) {
			$this->apiAddress = "https://api.dev-wx.281.com.cn/v1";
		}
		if (YII_ENV == 'beta') {
			$this->apiAddress = "https://api.beta-wx.281.com.cn/v1";
		}
		if (YII_ENV_PROD) {
			$this->apiAddress = "https://api.serv-wx.281.com.cn/v1";
		}

		return parent::init(); // TODO: Change the autogenerated stub
	}

	//小帮出行
	public function actionTrip()
	{

		$result['access_token']    = 'token';
		$result['unionId']         = $this->_wxUnionId;
		$result['openId']          = $this->_wxOpenId;
		$result['role']            = 'guest';
		$result['wx_access_token'] = isset($this->_wxInfo['token']) ? $this->_wxInfo['token'] : null;

		if ($this->_userId) {
			$token =  WxClientHelper::setAccessToken($this->_userId);
			$result['role']         = 'member';
			$result['access_token'] = $token;
			WxClientHelper::updateAccessToken($this->_userId,$token);
		}
		$result['api_address'] = $this->apiAddress;

		return $this->render("trip", $result);
	}

	//小帮快送
	public function actionErrand()
	{
		$result['access_token']    = 'token';
		$result['unionId']         = $this->_wxUnionId;
		$result['openId']          = $this->_wxOpenId;
		$result['role']            = 'guest';
		$result['wx_access_token'] = isset($this->_wxInfo['token']) ? $this->_wxInfo['token'] : null;

		if ($this->_userId) {
			$token =  WxClientHelper::setAccessToken($this->_userId);
			$result['role']         = 'member';
			$result['access_token'] = $token;
			WxClientHelper::updateAccessToken($this->_userId,$token);
		}
		$result['api_address'] = $this->apiAddress;

		return $this->render("errand", $result);

	}

	//企业送
	public function actionBiz()
	{
		$result['access_token']    = 'token';
		$result['unionId']         = $this->_wxUnionId;
		$result['openId']          = $this->_wxOpenId;
		$result['role']            = 'guest';
		$result['wx_access_token'] = isset($this->_wxInfo['token']) ? $this->_wxInfo['token'] : null;

		if ($this->_userId) {
			$token =  WxClientHelper::setAccessToken($this->_userId);
			$result['role']         = 'member';
			$result['access_token'] = $token;
			WxClientHelper::updateAccessToken($this->_userId,$token);
		}
		$result['api_address'] = $this->apiAddress;

		return $this->render("biz", $result);
	}
}
