<?php

namespace common\models\orders;

/**
 * This is the ActiveQuery class for [[Order]].
 *
 * @see Order
 */
class OrderQuery extends \yii\db\ActiveQuery
{
	/*public function active()
	{
		return $this->andWhere('[[status]]=1');
	}*/

	/**
	 * @inheritdoc
	 * @return Order[]|array
	 */
	public function all($db = null)
	{
		return parent::all($db);
	}

	/**
	 * @inheritdoc
	 * @return Order|array|null
	 */
	public function one($db = null)
	{
		return parent::one($db);
	}

	public function innerErrand($params=[])
	{
		return parent::innerJoin(OrderErrand::tableName(), Order::tableName() . ".order_id=" . OrderErrand::tableName() . ".order_id",$params); // TODO: Change the autogenerated stub
	}
}
