<?php

namespace pay\controllers;

use common\helpers\orders\BizSendHelper;
use Yii;
use yii\web\Controller;
use common\components\Ref;
/**
 * 小程序企业送 支付回调处理
 * Class WxpayController
 * @package pay\controllers
 */
class MiniBizWxpayController extends Controller
{
	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub

		$this->enableCsrfValidation = false;
	}

	//企业送支付
	public function actionBizOrderPayment()
	{
		$response = Yii::$app->mini_biz->getPayment()->handlePaidNotify(function ($notify, $fail) {

			Yii::$app->debug->pay_info("mini_biz_order_payment_notify", $notify);
			if ($notify['return_code'] === 'SUCCESS') { // return_code 表示通信状态，不代表支付状态
				// 用户是否支付成功
				if ($notify['result_code'] === 'SUCCESS') {

					$trade_no       = $notify['transaction_id'];
					$transaction_no = $notify['out_trade_no'];
					$fee            = $notify['total_fee'] * 0.01;
					$data           = json_encode($notify);
					$orderRes       = BizSendHelper::orderPaymentSuccess($transaction_no, $trade_no, Ref::PAYMENT_TYPE_WECHAT, $fee, "微信异步回调", $data);
					if ($orderRes) {
						return true;
					}
				}
			}

			return false; //默认未处理完成，让微信继续回调
		});

		return $response;
	}
}
