<?php
/**
 * @link http://www.281.com.cn/
 * @copyright Copyright (c) 2014 中山市中辰信息科技有限公司
 * @license http://www.281.com.cn/license
 * User: Andy Wong(黄燕弟)
 * Date: AndyWong 2018/4/17
 */

namespace api\modules\api\controllers;

use common\components\ControllerAPI;
use Yii;
use yii\web\UnauthorizedHttpException;

/**
 * Default controller for the `api` module
 */
class ControllerAccess extends ControllerAPI
{
	public $user_id;        //用户ID

	public function _init()
	{
		parent::_init(); // TODO: Change the autogenerated stub
	}

	public function beforeAction($action)
	{
		$this->enableCsrfValidation = false;

		$key = Yii::$app->request->headers->get('access-key');

		if (parent::beforeAction($action)) {

			$password = YII_ENV_PROD ? "81e6cef4add07d11b52e2175ada8282b" : "c1a89700c3b6b1ac8caa65e8424a404a";
			if ($key == $password) {

				return true;
			}
		}

		throw new UnauthorizedHttpException('Invalid key.', 401);

	}

	public function verbs()
	{
		return ['*' => ['POST']];
	}

	public function handleFailure($message = null)
	{
		$this->_code    = -200;
		$this->_message = $message ? $message : "操作失败";
	}
}
