<?php

namespace api\modules\api\controllers;

use common\components\ControllerAPI;
use Yii;

/**
 * Default controller for the `v1` module
 */
class SiteController extends ControllerAPI
{


	public function _init()
	{
		parent::_init(); // TODO: Change the autogenerated stub
	}

	public function actionIndex()
	{
		echo "hello backend API";

		exit;
	}
}