<?php

namespace api_user\modules\v1\controllers;

use api_user\modules\v1\helpers\StateCode;
use common\components\ControllerAPI;
use common\helpers\users\UserHelper;
use Yii;
use yii\web\UnauthorizedHttpException;

/**
 * Default controller for the `v1` module
 */
class ControllerAccess extends ControllerAPI
{
	public $userToken;        //返回个推表
	public $user_id;        //用户ID
	public $provider_id;    //小帮ID
	public $is_provider = false;

	public function _init()
	{
		parent::_init(); // TODO: Change the autogenerated stub
	}

	public function beforeAction($action)
	{
		$this->enableCsrfValidation = false;

		$access_token = Yii::$app->request->getBodyParam("access_token");
		if (parent::beforeAction($action)) {


			if ($this->whiteList()) {    //不用授权 白名单
				return true;
			}

			$newToken = UserHelper::getUserToken($access_token);
			if ($newToken) {

				$this->user_id     = $newToken['user_id'];
				$this->provider_id = $newToken['provider_id'];    //未申请小帮，该值为0

			} else {
				throw new UnauthorizedHttpException('You are requesting with an invalid credential.', 20000);
			}

			return true;
		} else {

			throw new UnauthorizedHttpException('No access token.', 401);
		}
	}

	public function verbs()
	{
		return ['*' => ['POST']];
	}

	public function setCodeMessage($code)
	{
		$this->_code    = $code;
		$this->_message = StateCode::get($code);
	}

	public function whiteList()
	{
		$result     = false;
		$actionList = [
			'v1/utils/image-callback',  //阿里云图片回调
			'v1/utils/startup-ad',       //启动页广告
			'v1/utils/popup-ad',         //弹窗广告
		];

		if (in_array($this->action->getUniqueId(), $actionList)) {
			$result = true;
		}

		return $result;
	}

}
